services:
  rails:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: clubroom-rails
    container_name: clubroom-rails
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - RAILS_ENV=production
    volumes:
      - public:/app/public

  next:
    container_name: clubroom-next
    image: clubroom-next
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rails

  db:
    image: postgres:15.1-alpine
    restart: always
    container_name: clubroom-postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: clubroom_production

  nginx:
    container_name: clubroom-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 54020:3080
      - 54030:4080
    depends_on:
      - rails
      - next
    volumes:
      - public:/app/public

volumes:
  database:
  public:
