AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
Style/AsciiComments:
  Enabled: false
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
StringLiterals:
  EnforcedStyle: double_quotes
