import Head from "next/head"
import { ReactNode } from "react"
import { Navbar } from "./navbar"

interface LayoutProps {
  children: ReactNode
}

export const Layout: React.FC<LayoutProps> = ({
  children,
}) => {
  return (
    <div>
      <Head>
        <title>Clubroom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        {children}
      </main>
    </div>
  )
}
