import Head from "next/head"
import { ReactNode } from "react"
import { Navbar } from "./Navbar"

interface LayoutProps {
  children: ReactNode
}

export const Layout: React.FC<LayoutProps> = ({
  children,
}) => {
  const mainStyle = {
    paddingTop: '80px'
  }

  return (
    <div>
      <Head>
        <title>Clubroom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className="container" style={mainStyle}>
        {children}
      </main>
    </div>
  )
}
