export enum TestID {
  TEST = 'test',
  ALERT = 'alert',
  ALERT_CLOSE = 'alert-close',
  LOGIN_EMAIL = 'login-email',
  LOGIN_PASSWORD = 'login-password',
  LOGIN_SUBMIT = 'login-submit',
  SIGNUP_LINK = 'signup-link',
  SIGNUP_EMAIL = 'signup-email',
  SIGNUP_NAME = 'signup-name',
  SIGNUP_PASSWORD = 'signup-password',
  SIGNUP_PASSWORD_CONFIRMATION = 'signup-password-confirmation',
  SIGNUP_SUBMIT = 'signup-submit',
  DROPDOWN_ACTION_BUTTON = 'dropdown-action-button',
  FORM_ERROR = 'form-error',
  TALK_LIST_BUTTON = 'talk-list-button',
  TALK = 'talk',
  TALK_ROW = 'talk-row',
  TALK_FORM = 'talk-form',
  TALK_FORM_INPUT = 'talk-form-input',
  TALK_FORM_SUBMIT = 'talk-form-submit',
}
